# Generated by Django 4.0.5 on 2022-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('start', 'start'), ('doing', 'doing'), ('success', 'success'), ('fail', 'fail')], max_length=31)),
            ],
        ),
    ]
